from django.conf.urls import patterns,url

urlpatterns = patterns('',
    url(r'^$','grumblrApp.views.index'),
    url(r'^index.html$', 'grumblrApp.views.index', name="grumblrApp_index"),
    url(r'^home.html$', 'grumblrApp.views.home',name="grumblrApp_home"),
    url(r'^profile.html$', 'grumblrApp.views.profile',name="grumblrApp_profile"),
    url(r'^profile_others.html/(?P<id>\d+)$', 'grumblrApp.views.profile_others',name="grumblrApp_profile_others"),
    url(r'^profile_others.html/(?P<username>\w+)$', 'grumblrApp.views.profile_others_username',name="grumblrApp_profile_others_username"),
    url(r'^pro_edit.html$', 'grumblrApp.views.profile_edit',name="grumblrApp_pro_edit"),
    url(r'^edit-entry/(?P<id>\d+)$', 'grumblrApp.views.edit_entry', name="grumblrApp_edit"),
    url(r'^search.html$', 'grumblrApp.views.search',name="grumblrApp_search"),
    url(r'^myregister$', 'grumblrApp.views.myregister',name="grumblrApp_myregister"),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'grumblrApp.views.confirm_registration', name="confirm"),
    url(r'^mylogin$', 'grumblrApp.views.mylogin',name="grumblrApp_mylogin"),  
    url(r'^mylogout$', 'grumblrApp.views.mylogout',name="grumblrApp_mylogout"),  
    url(r'^additem$', 'grumblrApp.views.additem',name="grumblrApp_additem"),
    #url(r'^addcomment$', 'grumblrApp.views.comment',name="grumblrApp_comment"), 
    url(r'^addcomment/(?P<id>\d+)/(?P<page>\d+)$', 'grumblrApp.views.comment',name="grumblrApp_comment"),
    url(r'^addcomment_dynamic/(?P<id>\d+)/(?P<page>\d+)$', 'grumblrApp.views.comment_dynamic', name="grumblrApp_comment_dynamic"),
    url(r'^comment_js/(?P<id>\d+)/(?P<page>\d+)$', 'grumblrApp.views.comment_js', name="grumblrApp_comment_JS"),
    url(r'^addfollowing$', 'grumblrApp.views.addfollowing',name="grumblrApp_addfollowing"),
    url(r'^addunfollowing$', 'grumblrApp.views.addunfollowing',name="grumblrApp_addunfollowing"),
    url(r'^addblocking$', 'grumblrApp.views.addblocking',name="grumblrApp_addblocking"),
    url(r'^addunblocking$', 'grumblrApp.views.addunblocking',name="grumblrApp_addunblocking"),
    url(r'^dlike/(?P<id>\d+)/(?P<page>\d+)$', 'grumblrApp.views.dlike',name="grumblrApp_dlike"),
    #url(r'^dlike_js/(?P<id>\d+)/(?P<page>\d+)$', 'grumblrApp.views.dlike_js',name="grumblrApp_dlike_JS"),
    url(r'^deleteitem/(?P<id>\d+)$', 'grumblrApp.views.deleteitem',name="grumblrApp_deleteitem"),
    url(r'^photo_id/(?P<id>\d+)$', 'grumblrApp.views.get_photo', name="grumblrApp_photo"),
    url(r'^photo_username/(?P<username>\w+)$', 'grumblrApp.views.get_photo_username', name="grumblrApp_photo_username"),
    url(r'^photo_userid/(?P<userid>\d+)$', 'grumblrApp.views.get_photo_userid', name="grumblrApp_photo_userid"),
    url(r'^allcomments/(?P<id>\d+)$', 'grumblrApp.views.get_all_comments',name="grumblrApp_allcomments"),
    url(r'^updategrumbls/(?P<id>\d+)$', 'grumblrApp.views.get_update_grumbls'),
    url(r'^alldlikes/(?P<id>\d+)$', 'grumblrApp.views.get_all_dlikes'),
    url(r'^changepassword$', 'grumblrApp.views.changepassword', name="grumblrApp_changepassword"),
    url(r'^forgotPassword$', 'grumblrApp.views.forgotpassword', name="grumblrApp_forgotpassword"),
    url(r'^reset$', 'grumblrApp.views.reset', name="grumblrApp_reset"),
    url(r'^success_reset$', 'grumblrApp.views.success_reset', name="grumblrApp_success_reset"),
    url(r'^success_reset_confirm$', 'grumblrApp.views.success_reset_confirm', name="grumblrApp_success_reset_confirm"),
    url(r'^reset_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$','grumblrApp.views.reset_confirm', name='reset_confirm'),
    url(r'^getUserNameById/(?P<id>\d+)$','grumblrApp.views.getUserNameById', name='getUserNameById'),
                       
    #url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'grumblrApp/login'}),
)